[package]
name = "onex"
version = "0.1.3"
authors = ["Ben Weedon <ben@weedon.email>"]
edition = "2018"

[dependencies]
structopt = "0.3.20"
util = { path = "../util" }
zip = { version = "0.5.8", default-features = false }
